name: 'Testing XamlX'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  configuration: Release

jobs:
  build:

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build tests
      working-directory: tests
      run: |
          dotnet build -c ${{ env.configuration }} TestClasses/TestClasses.csproj
          dotnet build -c ${{ env.configuration }} CecilNetstandardTests/CecilNetstandardTests.csproj
          dotnet build -c ${{ env.configuration }} CecilTests/CecilTests.csproj
          dotnet build -c ${{ env.configuration }} XamlParserTests/XamlParserTests.csproj
          dotnet build -c ${{ env.configuration }} XamlX.Tests/XamlX.Tests.csproj

    - name: Run tests
      run: dotnet test -c ${{ env.configuration }} --no-build
